apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-content-deployment
spec:
  selector:
    matchLabels:
      app: new-content
  template:
    metadata:
      labels:
        app: new-content
    spec:
      containers:
      - name: newcontent
        image: ROUTE_TO_REGISTRY/newcontent:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: newcontent-service
spec:
  selector:
    app: new-content
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: newcontent-proxy
  labels:
    icpdata_addon: "true"
    icpdata_addon_version: "v1"
data:
  nginx.conf: |
    location /newcontent/
    {
    access_by_lua_file /nginx_data/checkjwt.lua;
    proxy_pass http://newcontent-service.iaf-demo-project.svc:80/;
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: newcontent-nav-ext
  labels:
    icpdata_addon: "true"
    icpdata_addon_version: "v1"
data:
  extensions: |
    [
      {
        "extension_point_id": "left_menu_folder",
        "extension_name": "newcontent_nav_folder",
        "display_name": "New Content",
        "order_hint": 200,
        "match_permissions": "",
        "meta": {},
        "details":
        {
          "icon": "nav/icons/unified-switcher"
        }
      },
      {
        "extension_point_id": "left_menu_item",
        "extension_name": "newcontent-nav-extn",
        "display_name": "Hello World!",
        "order_hint": 200,
        "match_permissions": "",
        "meta": {},
        "details": {
          "parent_folder": "newcontent_nav_folder",
          "href": "/newcontent"
        }
      }
    ]